#!/usr/bin/env bash

# testrunner script of lifesaver

# TODO: add a more exhaustive check for dependencies of lifesaver and
# its test suite

test_dir=$(dirname "$0")

if [[ -f $test_dir/.bats/bats/bin/bats ]]; then
    "$test_dir"/.bats/bats/bin/bats "$test_dir"/test.bats
elif command -v bats >/dev/null 2>&1; then
    bats_version=$(bats --version)
    echo "./.bats/bats/bin/bats couldn't be found."
    echo "You may need to initialize the bats git submodules"
    echo "${bats_version} was found in your system and used to run lifesaver tests:"
    echo
    bats "$test_dir"/test.bats
else
    echo "./.bats/bats/bin/bats couldn't be found."
    echo "You may need to initialize the bats git submodules"
    echo "'bats' couldn't be found in the system."
    echo "Unable to run 'lifesaver' tests."
fi
